### ISSUE TITLE
feature request - SKIP_CLONE if .git/config exists

### ISSUE THREAD

**Issue by ITJamie** [linkyard/docker-git-sync#1]
right now SKIP_CLONE skips the clone step. it would be nice to have an additional config to skip clone ONLY if .git/config file exists. 
this would be very useful to make sure the data dir actually has a repo setup

**Comment by RandomNinjaAtk** [comment]
Just stumbled across this project and I agree, that this is much needed...

**Comment by RandomNinjaAtk** [comment]
A workaround that I figured out that solves this using docker-compose...

docker-compose.yaml
```
services:
  git_sync:
    image: linkyard/git-sync
    container_name: git_sync
    user: 99:100
    volumes:
      - /path/to/git-sync:/data
    environment:
      - REPO=https://github.com/user/repo.git
      - INTERVAL=120
      - BRANCH=main
    command: bash -c "rm -rf /data/{*,.*} 2>/dev/null; /opt/bin/git-sync.sh"
```

By wiping the directory at every container start, it will perform a fresh clone/pull and then continue syncing at an interval with no errors... Its not ideal but works....
